version: "3.4"

services:
  mongodev:
    image: mongo:4.4
    container_name: mongodev
    volumes:
      - ./.data/db:/data/db/
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 27017:27017
    command: ["--replSet", "rs0", "--bind_ip_all"]
